default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: product_project
  pool: 5
  username: root
  password: 123456789
  host: 127.0.0.1

production:
  url: <%= ENV['DATABASE_URL'] %>

